// Generated by https://quicktype.io

export interface Reporteventa {
    codigo:         number;
    fecha:          string;
    codigo_cliente: number;
    modo_pago:      string;
    total:          number;
    producto:       Producto[];
}

export interface Producto {
    codigo:          number;
    codigo_producto: number;
    codigo_venta:    number;
    codigo_vendedor: number;
    cantidad:        number;
    nombre:          string;
    url_foto:        string;
}
